### PR TITLE
Clarify the explanation of cascades.

### PR DESCRIPTION
**Pull request by matta**
The new wording explains what a cascade is first, then its basic syntax,
then gives an example.  I found this clearer than mixing the explanation of
what a cascade is with descriptions of two contrasting examples, one of
them far from the current text.

### CODE REVIEW

**Review by hilaire — COMMENTED** [review]
Your text seems incomplete. Can you review it? Thanks

**Comment by matta** [comment]
I re-read both the diff and the commit message. I feel it is complete. It would help me to hear from you what you found confusing about it.

Alternatively, we can just drop this PR. I found it confusing to refer back to an example that was far back in the text (I happened to read the two sections on different days). I think it would be slightly better to describe a cascade in a simpler way, but the way I did it in this PR is only one possibility.

**Comment by hilaire** [comment]
If I am not wrong, should it not be written as:

To send multiple messages **to the** same receiver a @dfn{cascade} can be used to
state the receiver once, followed by the cascade of messages separated
by semicolons. Here is our earlier @ref{hello2} code expressed with a
cascade:

**Comment by matta** [comment]
Of course!  I have fixed that up in this PR.

**Pull request merged**
